[features]
seeds = true
skip-lint = false
[programs.localnet]
staking = "7Q3Ct4TUFa1myoS3zY2FFskk4Qcupjxhw5yxTFMTKsG2"
lootbox = "sNFTZhMMtw7PjeWcBFqRnvMpgU8wVWo56dEriUeyvmG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kitan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
